version: '3.8'

services:
  api: 
    build: .
    ports:
      - "0:800"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/shortUrl
    volumes:
      - .:/usr/src/app
    restart: always
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: