version: '3.8'

services:
  api: 
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - mongodb+srv://adityakhandagale69:KR7Sm5bmUbgRMUwI@cluster0.0pq59kn.mongodb.net/
    volumes:
      - .:/usr/src/app
    restart: always
